name: Release tagged build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
          server-id: mavenpattern
          server-username: MAVEN_DEPLOY_USER
          server-password: MAVEN_DEPLOY_PASSWORD

      - name: Build and Publish with Maven
        run: mvn --batch-mode --update-snapshots deploy
        env:
          MAVEN_USER: ${{ secrets.MAVEN_DEPLOY_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_DEPLOY_PASSWORD }}

      - name: Release under current tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.RELEASE_VERSION }}"
          prerelease: false
          title: "${{ env.RELEASE_VERSION }}"
          files: target/*.jar
